@startuml Authenticate-Passwordless
title Passwordless Login
hide footbox

box "Client" #FloralWhite
    participant "Security Key" as Key
    actor  "User" as User
    participant "Browser" as Client
end box

box "Server" #GhostWhite
    participant "Sample-App(RP)\n\nhttp://localhost:8080" as RP
    participant "LINE-FIDO2-Server\n\nhttp://localhost:8081" as Server
end box

note over Client : login.html
User -> Client : Click **[Passwordless login]** Button

group 1. Get Auth Challenge
    Client -> RP : POST /authenticate/option
    RP -> Server : **Get Auth Challenge**\nPOST /fido2/auth/challenge
    note over Server : Generate Challenge&Option
    RP <-- Server : 200 OK\n - Challenge&Option
    Client <-- RP : 200 OK\n - Challenge&Option
end group

group 2. WebAuthn
    note over Client : navigator.credentials.get()
    Key <-- Client : Connect
    Key <- User : User Verification\n(PIN or Fingerprint)
    Key --> Client : Response\n - Assertion
end group

group 3. Verify Assertion
    Client -> RP : POST /login-fido2\n - Assertion
    RP -> Server : **Send Auth Response**\nPOST /fido2/auth/response\n - Assertion
    note over Server : Verify Assertion
    RP <-- Server : 200 OK\n - Verify Result(ok)

    RP -> Server : **Get Credential by CredentialId**\nPOST /fido2/credentials/{id}
    RP <-- Server : 200 OK\n - Credential

    note over RP : Check Credential
    note over RP : Spring Security Login
    Client <-- RP : 302 Redirect\n - /mypage
end group

Client -> RP : GET /mypage
Client <-- RP : 200 OK
note over Client : mypage.html

@enduml
