@startuml
title FIDO2 Registration
hide footbox

box "Client" #FloralWhite
    participant "Security Key" as Key
    actor  "User" as User
    participant "Browser" as Client
end box

box "Server" #GhostWhite
    participant "Sample-App(RP)\n\nhttp://localhost:8080" as RP
    participant "LINE-FIDO2-Server\n\nhttp://localhost:8081" as Server
end box

note over Client : mypage.html
User -> Client : Click Register Button

group 1. Get Reg Challenge
    Client -> RP : POST /register/option
    RP -> Server : POST /fido2/reg/challenge\n - ID&Param
    note over Server : Generate Challenge&Option
    RP <-- Server : 200 OK\n - Challenge&Option
    Client <-- RP : 200 OK\n - Challenge&Option
end group

group 2. WebAuthn
    note over Client : navigator.credentials.create()
    Key <-- Client : Connect
    Key <- User : User Verification
    Key --> Client : Response\n - Attestation
end group

group 3. Send Reg Response
    Client -> RP : POST /register/verify\n - Attestation
    RP -> Server : POST /fido2/reg/response\n - Attestation
    note over Server : Verify Attestation\nStore Credential to DB
    RP <-- Server : 200 OK\n - Verify Result(ok)
    Client <-- RP : 200 OK\n - Verify Result(ok)
end group

note over Client : Message\n- Registration Success

@enduml
