@startuml
title FIDO2 Device Registration
hide footbox

box "Client" #FloralWhite
    participant "Security Key" as Key
    actor  "User" as User
    participant "Browser" as Client
end box

box "Server" #GhostWhite
    participant "Sample-App(RP)\n\nhttp://localhost:8080" as RP
    participant "LINE-FIDO2-Server\n\nhttp://localhost:8081" as Server
end box

User -> Client : Click Register Button

group Get Reg Challenge
    Client -> RP : POST /register/option
    RP -> Server : POST /fido2/reg/challenge
    note over Server : Generate Challenge&Option
    RP <- Server : Response\n - Challenge&Option
    Client <- RP : Response\n - Challenge&Option
end group

group WebAuthn
    note over Client : navigator.credentials.create()
    Key <-- Client : Connect
    Key <- User : User Verification
    Key --> Client : Response\n - Attestation
end group

group Get Reg Challenge
    Client -> RP : POST /register/verify\n - Attestation
    RP -> Server : POST /fido2/reg/response\n - Attestation
    note over Server : Verify Attestation\nStore Credential to DB
    RP <- Server : Response\n - Verify Result(ok)
    Client <- RP : Response\n - Verify Result(ok)
end group

note over Client : Message\n- Registration Success

@enduml
